const questions = [
  {
    id: 1,
    question: "how many days in a leap year",
    answer: "366 days",
    votes: 99,
    author: "sammy guevara",
    comments: [],
  },
  {
    id: 2,
    question: "how many ways a batsman can get out",
    answer: "19",
    votes: 62,
    author: "Jessi james",
    comments: [],
  },
  {
    id: 3,
    question: "WHat is the price of iphone 15 expected in india",
    answer: "expected around 1 lakh 29 thousand",
    votes: 99,
    author: "khalid",
    comments: [],
  },
  {
    id: 4,
    question: "How many goal does ronaldo have in his name",
    answer: undefined,
    votes: 0,
    author: undefined,
    comments: [],
  },
  {
    id: 5,
    question: "What is the minimum wage salary in australia",
    answer:
      "Usually it is pretty low but compared to amaerica, it is better at around 4399 AUD per anum",
    votes: 99,
    author: "sammy guevara",
    comments: [],
  },
  {
    id: 6,
    question: "Cricketer with highest score",
    answer: "Sir sachin tendulkar",
    votes: 999,
    author: "brian lara",
    comments: [],
  },
  {
    id: 7,
    question: "where is one day world cup in 2023",
    answer: "India and srilanka",
    votes: 29,
    author: "Vikrant",
    comments: [],
  },
  {
    id: 8,
    question: "what is the net worth of elon musk",
    answer: undefined,
    votes: 0,
    author: undefined,
    comments: [],
  },
  {
    id: 9,
    question: "What is the bet tech stcak to start career in web development",
    answer: undefined,
    votes: 0,
    author: undefined,
    comments: [],
  },
];

module.exports = questions;
